site_name: ICTG'S Handover Haven
nav:
  - Introduction: index.md
  - About: about.md
  - Changelog: changelog.md
  - Getting Started:
      - Overview: getting-started/index.md
      - How to Use: getting-started/how-to-use.md
      - Template: getting-started/template.md
      - System Template: getting-started/system-template.md
      - Common Request Template: getting-started/common-request-template.md
      - Onboarding Guide: getting-started/onboarding-guide.md
      - Glossary: getting-started/glossary.md
  - Companies:
      - Overview: companies/index.md
      - Philequity Management: companies/pemi/index.md
      - Vantage Equities: companies/vei/index.md
      - Vantage Financial: companies/vfc/index.md
  - Handovers:
      - Introduction: handovers/introduction.md
      - Lowie Dave Dichoson:
          - About Me: handovers/lowie-dave-dichoson/about-me.md
          - Systems: 
                - Eterminal: handovers/lowie-dave-dichoson/systems/eterminal.md
                - Esettlement: handovers/lowie-dave-dichoson/systems/esettlement.md
                - LOI Generator: handovers/lowie-dave-dichoson/systems/loi-generator.md
                - Synapse: handovers/lowie-dave-dichoson/systems/synapse.md
                - Voyager: handovers/lowie-dave-dichoson/systems/voyager.md
                - Voyager FX: handovers/lowie-dave-dichoson/systems/voyager-fx.md
                - FTR Generator: handovers/lowie-dave-dichoson/systems/ftr-generator.md
                - Navision: handovers/lowie-dave-dichoson/systems/navision.md
                - Production Archiving: handovers/lowie-dave-dichoson/systems/production-archiving.md
                - Clientease Frontend: handovers/lowie-dave-dichoson/systems/clientease-frontend.md
                - Clientease Backend: handovers/lowie-dave-dichoson/systems/clientease-backend.md
          - Common Requests: 
                - Correcting Bridge Entries:
                     - Reverse Entries: handovers/lowie-dave-dichoson/common-requests/000-reverse-bridge-entries.md
                     - Re/create Entries: handovers/lowie-dave-dichoson/common-requests/001-recreation-of-bridge-entries.md
                     - Transfer Entries: handovers/lowie-dave-dichoson/common-requests/002-transfer-entries-to-navision.md
                - Backend Formulas: handovers/lowie-dave-dichoson/common-requests/003-backend-formulas-in-esettlement.md
                - Users List: handovers/lowie-dave-dichoson/common-requests/004-active-users-list.md
                - Manual Run of EOD Process: handovers/lowie-dave-dichoson/common-requests/005-manual-run-of-eod-process.md
theme:
  name: material
  icon:
    logo: octicons/rocket-16
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets