site_name: Handover Haven
nav:
  - Home: index.md
  - About: about.md
  - Changelog: changelog.md
  - Getting Started:
      - Overview: getting-started/index.md
      - How to Use: getting-started/how-to-use.md
      - Template: getting-started/template.md
  - Handovers:
      - Overview: handovers/overview.md
      - Lowie Dave Dichoson:
          - Overview: handovers/lowie-dave-dichoson/overview.md
          - Philequity Management, Inc.: handovers/lowie-dave-dichoson/philequity-management-inc/overview.md
          - Vantage Equities, Inc.: handovers/lowie-dave-dichoson/vantage-equities-inc/overview.md
          - Vantage Financial Corp.: handovers/lowie-dave-dichoson/vantage-financial-corp/overview.md
theme:
  name: shadcn
  show_title: true
  show_stargazers: true
  pygments_style:
        light: shadcn-light
        dark: github-dark
  icon: heroicons:rocket-launch
  topbar_sections: true
  show_datetime: true
  accent: "oklch(64.5% 0.246 16.439)"
